services:
    nginx:
        image: nginx_custom
        build: nginx_custom
        restart: always
        depends_on:
            - phpap
        ports:
            - "80:80"
            #- "443:443"
        networks:
            - default
        #logging:
        #    driver: "journald"

    phpap:
        image: apatchphp_custom
        build: apatchphp_custom
        restart: always
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        networks:
            - default
        environment:
            TZ: Asia/Tokyo
        #logging:
        #    driver: "journald"
        volumes:
            - ./apatchphp_custom/contents/:/var/www/html/

    mariadb:
        image: mariadb_custom
        build: mariadb_custom
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: phpTraining
            MYSQL_USER: phpUser
            MYSQL_PASSWORD: phpPassword
        networks:
            - default
        #logging:
        #    driver: "journald"
            #options:
            #    max-size: "50m"
            #    max-file: "3"
        # volumes:
        #     - ./db_data:/var/lib/mysql

    mongodb:
        image: mongodb_custom
        build: mongodb_custom
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongo
            MONGO_INITDB_DATABASE: alertlist
        #volumes:
        #    - ./mongodb_data:/data/db
    radis:
        image: redis_custom
        build: redis_custom
        restart: always
        ports:
            - "6379:6379"
        networks:
            - default
        # command: redis-server --appendonly yes
        #volumes:
        #    - /radis_data:/data
